name: _29035f
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  go_router: ^15.1.2
  hive: ^2.2.3
  google_fonts: ^6.2.1
  flutter_neumorphic_plus: ^3.4.0
  country_code_picker: ^3.3.0
  flutter_secure_storage: ^9.2.4
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/images/splash_illustration/